main: com.polargalaxy.EmojiX
name: EmojiX
version: 1.0
author: pphelix, published via polargalaxy.com
description: Refined Minecraft-compliant UTF-8 emoji for chat and signs with link escaping and no discoloration
