# +------------------------------------------------------+
# <    Main config - Visit: https://polargalaxy.com/     >
# +------------------------------------------------------+

# Please refer to the Github Wiki for guidance: https://github.com/PolarGalaxyMC/emojix/wiki
# !---- Color Code format uses '&' ----!

# +---------------------+
# <    Main messages    >
# +---------------------+

# Suffix - Plugin name 
suffix:
  color: "&9"

# Help - Help message (displayed after plugin name once EmojiX command has been used)
help:
  string: "[Hover for help]"
  color: "&f"

# Noemoji - Message to those who don't have access to any emojis and have used the EmojiX command
noemoji:
  string: "You don't have any emojis!"
  color: "&c"

# Nopermission - Message to those who don't have access to use the EmojiX command
nopermission:
  string: "You don't have permission to use this command!"
  color: "&c"

# +-------------------------+
# <    Tooltip messages    >
# +-------------------------+
# (tooltip: The content of the box that is generated on hover)

# Tooltip-suffix - Description for suffix tooltip
tt-suffix:
  string: "EmojiX Plugin!"
  color: "&a"

# Tooltip-help - Description for help tooltip
tt-help:
  string: "Hover over an Emoji to view the syntax! \nYou can then type out the syntax in chat to use the Emote\n
  or shift-click to auto-magically put it in chat!"
  color: "&a"

# Tooltip-noemoji - Description for no emojis tooltip
tt-noemoji:
  string: "You can earn emojis by playing the game!"
  color: "&a"

# Tooltip-emoji - The color of the tooltip which shows syntax for hovered emoji
tt-emoji:
  color: "&7"